name: MoneyPouch
main: MoneyPouch\Main
version: 2.0.0-B1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: VMPE Development Team
description: MoneyPouch
commands:
 moneypouch:
  description: "Give a money pouch"
